name: Build Gradle project

on:
  push:

jobs:
  build-java-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Gradle wrapper
        run: make wrapper
      - name: Build project
        run: make build
      - name: Test project
        run: make test